development:
# sqlite3
  adapter: sqlite3
  database: db/development.sqlite3
  timeout: 5000
# mysql
  # adapter: mysql
  # database: example_development
  # username:
  # password:
  # host: localhost
# postgresql
  # adapter: postgresql
  # database: example_development
  # username:
  # password:
  # host: localhost

test:
  adapter: sqlite3
  database: db/test.sqlite3
  timeout: 5000

production:
  adapter:
  database:
  username:
  password:
  host:
